services:
  bundle: &bundle
    env_file: .env
    tty: true
    stdin_open: true
    build:
      context: .
      args:
        BUNDLE_GITHUB__COM: ${BUNDLE_GITHUB__COM}
        BUNDLE_GEM__FURY__IO: ${BUNDLE_GEM__FURY__IO}
        WITH: test development
    entrypoint: bundle
    command: version
    volumes:
      - .:/usr/src/app:delegated
      - bundle:/usr/local/bundle
      - ${LOCAL_GEM_PATH:-..}:/local

  server:
    <<: *bundle
    # command: exec ruby ./app.rb
    # command: exec rails s -b 0.0.0.0
    
  console:
    <<: *bundle
    # command: exec console
    # command: exec rails c
    
  rspec:
    <<: *bundle
    entrypoint: bundle exec rspec
    command: --help

volumes:
  bundle: {}
